export enum IconName {
  icArrowBendDownRight = "icArrowBendDownRight",
  icArrowBendUpLeft = "icArrowBendUpLeft",
  icArrowClockwise = "icArrowClockwise",
  icChartLine = "icChartLine",
  icCheckCircle = "icCheckCircle",
  icCurrencyDollarSimple = "icCurrencyDollarSimple",
  icEyedropper = "icEyedropper",
  icFaders = "icFaders",
  icGithub = "icGithub",
  icInfo = "icInfo",
  icInstagram = "icInstagram",
  icLinkedin = "icLinkedin",
  icMoon = "icMoon",
  icPaintBucket = "icPaintBucket",
  icPalette = "icPalette",
  icPaperPlaneTilt = "icPaperPlaneTilt",
  icPlus = "icPlus",
  icPulse = "icPulse",
  icSun = "icSun",
  icUser = "icUser",
  icUsers = "icUsers",
  icWarningCircle = "icWarningCircle",
  icXCircle = "icXCircle",
  icX = "icX",
}
