export const WCAG_AA_NORMAL_TEXT_CONTRAST_RATIO = 4.5
export const WCAG_AAA_NORMAL_TEXT_CONTRAST_RATIO = 7
export const WCAG_AA_LARGE_TEXT_CONTRAST_RATIO = 3
export const WCAG_AAA_LARGE_TEXT_CONTRAST_RATIO = 4.5
export const WCAG_AA_UI_CONTRAST_RATIO = 3
